ARG NODE_VERSION=alpine3.23

FROM node:${NODE_VERSION} AS dev

ENV NODE_ENV=development

WORKDIR /crypto-tracker-vue3-vite

COPY package.json package-lock.json* ./

RUN --mount=type=cache,target=/root/.npm npm install

COPY . .

RUN chown -R node:node /crypto-tracker-vue3-vite

USER node

EXPOSE 5173

CMD [ "npm", "run", "dev", "--", "--host" ]